Add files via upload
meogol/Diplom pull request #1
Opened 2018-12-13 06:09 UTC by meogol

2018-12-13 19:00 UTC, troepolik requested changes

2018-12-13 19:00 UTC, troepolik commented on Fild.cs
> +    class Fild
похоже проект не полный, я так и не нашел ниодного филда у тебя, реализующего IField
закинь в реквест тот проект который ты анализировал, пусть он будет в солюшене.

2018-12-13 19:00 UTC, troepolik commented on MethodAnalisysWalker.cs
> +            var interfaceNames = node.DescendantNodes().OfType<SimpleBaseTypeSyntax>().Where(c => c.GetFirstToken().Text == "IFild").FirstOrDefault();//сравнимаем полученные имена с IFild и в случае
что-то мне подсказывает что это очень наивный способ определения наследования от IField.
мы не можем опираться на имя, нам нужно определять реальный класс. т.к имена могут совпадать- в бизнес коде вполне моет найтись свой IField  из другого неймспейса.
к тому же, сюда ты закидываешь корневой узел документа. но берешь только 1й элемент. надо учитывать тот случай, когда в документе могут быть объявлены несколько классов.

у рослина есть 2й режим анализатора. когда известна модель классов со всеми связями и наследованиями, мб имеет смысл воспользоваться ею.
т.к классы, содержащие  CreateFields  будут наследоваться друг от друга, добавлять новые филды и изспользовать филды наследника , добвлять новые параметры, переопределять их и т.п это все придется учитывать.

2018-12-13 19:00 UTC, troepolik commented on MethodAnalisysWalker.cs
> +            if (isIFild.Contains(nameType))//из всей строки берем только первые 2 значения: тип и имя объекта, проверяем, есть ли такой тип в isIFild
слишком наивный способ определения типа. см. снизу, я расписал более подробно.

2019-01-12 17:55 UTC, troepolik requested changes

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +            foreach (var file in project.Documents)
а нельзя оперировать не файлами, а какими-то объектными моделями? вроде как проект уже скомпилирован, было бы наверное логичнее, просто перебрать все классы определенного типа... может есть такая возможность.
просто потом к этому добавить наследование т.е class B : A  и мы должны будем понять что у класса B  уже есть какой-то набор параметров , определенных в A , возможно (это не точно) это будет удобнее если мы изначально будем оперировать именно какой-то скомпилированной информацией, а не документами...
как считаешь?

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +                    SyntaxTree tree = file.GetSyntaxTreeAsync().Result;
для начала пойдет, но потом тебе нужно будет все -таки разобраться что такое async )

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +        public void VisitMethodDeclaration(SyntaxNode node)//перегружаем visitMethodDeclaration под наше дерево и ищем нужный метод. дефолтный визит будет гулять по дереву за нас
зачем писать так коментарии, когда есть нормальные саммари над методами.
и что-то тут не так. ты пишешь что ты перегружаешь VisitMethodDeclaration, но не вижу override
хотя может VisitMethodDeclaration абстрактный и шарп позволяет не писать слово override в этом случае..
но нет, ты же вызываешь base.VisitMethodDeclaration(method); значит метод не абстрактный...
понятия не имею как это вообще работает...

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +                if (a == "IFild")
в итоге ты получил реализацию ничем не лучше предыдущей. скомпилированная реализация должна быть тебе больше информации, чем обычная. тут нельзя операться на строку IFild, нужно либо оперировать реальным интерфейсом IFild т.е использовать ф-ю Type.IsSubclassOf(Type)
как-то так : убрать .Select(p => p.Name).ToList() - нам нужны не имена а сами типы.
a.IsSubclassOf(typeof(IField))
если нельзя получить объект типа, в чем я сильно сомневаюсь, то нужно оперировать FullName  , (вместе с неймспейсом). .Select(p => p.FullName)

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +        string GetInterfacesNames(SemanticModel sModel, IdentifierNameSyntax identifier)//получаем реализуемые объектом интерфейсы
нехватает развернутых комментариев. например что приходит на вход метода. саммари позволяет оставлять комментарии прямо к аргументам.
что такое sModel, identifier откуда они берутся, что короче сюда нужно передавать по смыслу. непонятно.
на сколько я понял sModel у тебя на уровне класса сидит, поэтому её вроде как передавать не надо.
сигнатура должна быть примерно такая:
/// метод проверяет что класс реализует интерфейс
bool CheckProvideInterface(Type interface, <какой-то тип аргумента> classNode)

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +        {//узел представляет строку операции(fild1.fild2 = fild2;) из этого берем первый и последний токен- имена филдов. соответственно первый зависит от последнего
здесь комментарий хороший, везде нужны такие

2019-01-12 17:55 UTC, troepolik commented on MethodAnalisysWalker.cs
> +                textFile.Close();
следущий шаг, писать в файл будем в конце. а походу анализа будем формировать информационные объекты с информацией о классах, какие в них филды содержатся, и какие эти филды имеют зависимости.
т.е цель - составить модель: какие классы есть в проекте, какие филды внутри них, какие параметры имеют филды.
классы можешь посмотреть в моих .tt  файлах, там в конце 2го файла они объявляются - класс информации и филде, класс информации о самой сущности, класс параметра, проперти и т.п. не все из них тебе нужны, только класс самой бизнес- сущности, класс филда, возможно там еще сам параметр тоже ввиде класса, но возможно просто дикшенари внутри филда, не помню.

2019-01-16 06:22 UTC, meogol commented
не пойму что должно быть на выходе. Мне надо опираться на
классы LocalizeProperty и DealClassInfo? сделать класс с полями: имя
класса, ParamInfo?

И еще, через рослин я не могу сравнить типы) через Type я буду получать тип
узла, а не объекта. Оперирую я интерфейсом ITypeSymbol
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.itypesymbol?view=roslyn-dotnet
Как раз его дает мне семантическая модель из компиляции и
метод GetTypeInfo.Type. Все остальное лишь информацию, но не тип. Сделал
через имя с неймспейсом.

сб, 12 янв. 2019 г. в 20:56, Aleksey Troepolskiy <notifications@github.com>:

> *@troepolik* requested changes on this pull request.
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1#discussion_r247318056>:
>
> > +using System.Threading.Tasks;
> +
> +namespace ConsoleApp1
> +{
> +    class MethodAnalisysWalker : CSharpSyntaxWalker
> +    {
> +        /// <summary>
> +        /// путь к папке проекта(для записи .тхт)
> +        /// </summary>
> +        public string projectPath { get; set; }
> +
> +        SemanticModel model;
> +        public void ProjectAnalysis(Project project)
> +        {
> +            Compilation compilation = project.GetCompilationAsync().Result;
> +            foreach (var file in project.Documents)
>
> а нельзя оперировать не файлами, а какими-то объектными моделями? вроде
> как проект уже скомпилирован, было бы наверное логичнее, просто перебрать
> все классы определенного типа... может есть такая возможность.
> просто потом к этому добавить наследование т.е class B : A и мы должны
> будем понять что у класса B уже есть какой-то набор параметров ,
> определенных в A , возможно (это не точно) это будет удобнее если мы
> изначально будем оперировать именно какой-то скомпилированной информацией,
> а не документами...
> как считаешь?
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1#discussion_r247318080>:
>
> > +{
> +    class MethodAnalisysWalker : CSharpSyntaxWalker
> +    {
> +        /// <summary>
> +        /// путь к папке проекта(для записи .тхт)
> +        /// </summary>
> +        public string projectPath { get; set; }
> +
> +        SemanticModel model;
> +        public void ProjectAnalysis(Project project)
> +        {
> +            Compilation compilation = project.GetCompilationAsync().Result;
> +            foreach (var file in project.Documents)
> +            {
> +                if (file.Name== "Entity.cs") {
> +                    SyntaxTree tree = file.GetSyntaxTreeAsync().Result;
>
> для начала пойдет, но потом тебе нужно будет все -таки разобраться что
> такое async )
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1#discussion_r247318110>:
>
> > +        public string projectPath { get; set; }
> +
> +        SemanticModel model;
> +        public void ProjectAnalysis(Project project)
> +        {
> +            Compilation compilation = project.GetCompilationAsync().Result;
> +            foreach (var file in project.Documents)
> +            {
> +                if (file.Name== "Entity.cs") {
> +                    SyntaxTree tree = file.GetSyntaxTreeAsync().Result;
> +                    model = compilation.GetSemanticModel(tree);
> +                    Visit(tree.GetRoot()); }
> +            }
> +        }
> +
> +        public void VisitMethodDeclaration(SyntaxNode node)//перегружаем visitMethodDeclaration под наше дерево и ищем нужный метод. дефолтный визит будет гулять по дереву за нас
>
> зачем писать так коментарии, когда есть нормальные саммари над методами.
> и что-то тут не так. ты пишешь что ты перегружаешь VisitMethodDeclaration,
> но не вижу override
> хотя может VisitMethodDeclaration абстрактный и шарп позволяет не писать
> слово override в этом случае..
> но нет, ты же вызываешь base.VisitMethodDeclaration(method); значит метод
> не абстрактный...
> понятия не имею как это вообще работает...
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1#discussion_r247319072>:
>
> > +            foreach (var method in methods)
> +            {
> +                string methodName = method.Identifier.ToString();
> +
> +                if (methodName == "CreateFilds")
> +                    base.VisitMethodDeclaration(method);
> +            }
> +        }
> +
> +        string GetInterfacesNames(SemanticModel sModel, IdentifierNameSyntax identifier)//получаем реализуемые объектом интерфейсы
> +        {//проверяем, есть ли среди них IFild, если есть, возвращаем имя класса
> +            ITypeSymbol nodeType = sModel.GetTypeInfo(identifier).Type;
> +            if (nodeType == null)
> +                return null;
> +            foreach (var a in nodeType.Interfaces.Select(p => p.Name).ToList())
> +                if (a == "IFild")
>
> в итоге ты получил реализацию ничем не лучше предыдущей. скомпилированная
> реализация должна быть тебе больше информации, чем обычная. тут нельзя
> операться на строку IFild, нужно либо оперировать реальным интерфейсом
> IFild т.е использовать ф-ю Type.IsSubclassOf(Type)
> как-то так : убрать .Select(p => p.Name).ToList() - нам нужны не имена а
> сами типы.
> a.IsSubclassOf(typeof(IField))
> если нельзя получить объект типа, в чем я сильно сомневаюсь, то нужно
> оперировать FullName , (вместе с неймспейсом). .Select(p => p.FullName)
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1#discussion_r247319103>:
>
> > +        }
> +
> +        public void VisitMethodDeclaration(SyntaxNode node)//перегружаем visitMethodDeclaration под наше дерево и ищем нужный метод. дефолтный визит будет гулять по дереву за нас
> +        {
> +            var methods = node.DescendantNodes().OfType<MethodDeclarationSyntax>();
> +
> +            foreach (var method in methods)
> +            {
> +                string methodName = method.Identifier.ToString();
> +
> +                if (methodName == "CreateFilds")
> +                    base.VisitMethodDeclaration(method);
> +            }
> +        }
> +
> +        string GetInterfacesNames(SemanticModel sModel, IdentifierNameSyntax identifier)//получаем реализуемые объектом интерфейсы
>
> нехватает развернутых комментариев. например что приходит на вход метода.
> саммари позволяет оставлять комментарии прямо к аргументам.
> что такое sModel, identifier откуда они берутся, что короче сюда нужно
> передавать по смыслу. непонятно.
> на сколько я понял sModel у тебя на уровне класса сидит, поэтому её вроде
> как передавать не надо.
> сигнатура должна быть примерно такая:
> /// метод проверяет что класс реализует интерфейс
> bool CheckProvideInterface(Type interface, <какой-то тип аргумента>
> classNode)
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1#discussion_r247319766>:
>
> > +            }
> +        }
> +
> +        string GetInterfacesNames(SemanticModel sModel, IdentifierNameSyntax identifier)//получаем реализуемые объектом интерфейсы
> +        {//проверяем, есть ли среди них IFild, если есть, возвращаем имя класса
> +            ITypeSymbol nodeType = sModel.GetTypeInfo(identifier).Type;
> +            if (nodeType == null)
> +                return null;
> +            foreach (var a in nodeType.Interfaces.Select(p => p.Name).ToList())
> +                if (a == "IFild")
> +                    return nodeType.Name;
> +            return null;
> +        }
> +
> +        public override void VisitExpressionStatement(ExpressionStatementSyntax node)
> +        {//узел представляет строку операции(fild1.fild2 = fild2;) из этого берем первый и последний токен- имена филдов. соответственно первый зависит от последнего
>
> здесь комментарий хороший, везде нужны такие
> ------------------------------
>
> In MethodAnalisysWalker.cs
> <https://github.com/meogol/Diplom/pull/1# [...]

2019-01-27 10:02 UTC, troepolik requested changes
1) поправь замечания, в том числе те, которые я писал в предыдущем ревью, не все были поправлены.
2) имей ввиду что твой код сейчас очень наивен и не учитывает наследования и другие фишки. я пока на это обращаю внимания, но ты должен держать это в голове, т.к рано или поздно поддержку нужно будет добавить. 
3) следующий этап - генерация графа по EntityInfo
мы слегка переделали генерацию в нашем репозитории, вынесли граф в отдельный класс. поэтому в понедельник я тебе пришлю свежий код, и длл с помощью которой граф создается.
если не пришлю, напиши мне.

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +            foreach (var file in project.Documents)
а есть ли возможность перебирать не файлы, а наоборот оттталкиваться от семантической модели: т.е выбрать из компиляции все классы с интерфейсом IFieldsEntity (интерефейс , который должна будет реализовавывать каждый наш анализируемый энтити-класс) далее из семантической модели этого класса получить синтаксическую (методом или какой-либо связью между классом и файлом).
без синтаксической модели нам нельзя обойтись? семантическая модель не дает информации что происходит в теле метода?

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +        public void VisitMethodDeclaration(SyntaxNode node)
тут не должно быть override ?

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +        string GetInterfacesNames(SemanticModel sModel, IdentifierNameSyntax identifier)
я в предыдущем ревью написал какая должна быть сигнатура метода. ты почему-то это проигнорировал и метод до сих пор ужасе и название не соответсвует тому что тут происходит

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +                if (a.ToString() == typeof(IFild).AssemblyQualifiedName.Split(',')[0])
зачем делать лишние действия если можно просто юзать FullName ?
и вообще использовать ToString() для какой-то логики- плохое решение, -он недает понять при чтении кода что конкретно ты ожидаешь получить. лучше используй какое-нить проперти.

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +        /// переменные nameFild... хранят названия типов
у тебя хромает логика названий переменных. если это тип филда, то и называй соответсвенно fieldType

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +            if (nameFilds.Count() == 3)
есть хороший паттерн оформления кода. "избегай длинных тел условий если это не требуется"
заметь что у тебя какое-то условие и дальшне длииинное тело и далее ничего не делается - нет else  или чего-то еще.
так зачем нам тогда усложнять код?
можно писать просто :
 if (nameFilds.Count() != 3)
return

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +                    if (entityInfo.lFieldInfo.Where(f => f.Name == fildOne.ToString()).LastOrDefault() != null)
зачем изобретать велосипед? возьми код из .tt  файлов.
в данному случае у тебя зачем-то LastOrDefault, вместо FirstOrDefault и вообще, почему не заюзал дикшенари?
короче, поизучай то что уже написано и не делай глупостей. если что-то непонятно по коду, приходи,объясню.

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +                        entityInfo.lFieldInfo.Where(f => f.Name == fildOne.ToString()).LastOrDefault().lParamInfo.Add(paramInfo);
о перфомансе ты явно не думаешь... 2 раза делать серч это лол.
и вообще у тебя должно быть дикшенари филдов а не список

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +                    entityInfo.lFieldInfo.Add(fieldInfo);
увы, я не понимаю почему ты 2 раза добавляешь параметр филду : там где ты по лямде ищешь филд и еще раз для вновь созданного филда...  это явно ошибка.

2019-01-27 10:02 UTC, troepolik commented on Analisys/MethodAnalisysWalker.cs
> +                    textFile.Close();
убрать отсюда запись в файл.

2019-01-27 10:02 UTC, troepolik commented on InfoClass/EntityInfo.cs
> +        public List<FieldInfo> lFieldInfo { get; set; }
должна быть дикшенари.

2019-01-27 10:02 UTC, troepolik commented on InfoClass/FieldInfo.cs
> +        public List<ParamInfo> lParamInfo { get; set; }
сейчас шарп позволяет писать сразу:
public List < ParamInfo > lParamInfo { get; set; } = new List < ParamInfo >();

2019-01-27 10:02 UTC, troepolik commented on ProjectAnalisys/Entity.cs
> +    class Entity
должно реализовывать интфейс IFieldsEntity  или наследоваться откласса, который его реализует. пусть это будет пока пустой интерфейс , просто это будет маркер по которому мы будем цепляться к анализируемым классам

2019-01-29 19:39 UTC, troepolik requested changes

2019-01-29 19:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +            var classSymbol = sModel.GetDeclaredSymbol(root.DescendantNodes().OfType<ClassDeclarationSyntax>().First());
как-то очень запутанно... ты точно не перемудрил?
у тебя в метод уже приходит ClassDeclarationSyntax node
но ты потом опять его получаешь через левое ухо
root.DescendantNodes().OfType< ClassDeclarationSyntax >().First()

2019-01-29 19:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +                if (fullNameInterface.ToString() == typeof(IFieldsEntity).FullName)
все это можно заменить  на одно короткое  условие
if(classSymbol.AllInterfaces.Any(i=>i.ToString() == typeof(IFieldsEntity).FullName))
...
кстати, ты опять игноришь замечания - убери здесь ToString(), сравнивай с пропертей

2019-01-29 19:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +        string GetInterfacesNames(IdentifierNameSyntax identifier)
переделать сигнатуру! уже в 3й раз говорю...
bool CheckRealizeInterface(Type interface, IdentifierNameSyntax identifier)

2019-01-29 19:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +                var NameFildTwo = nameFilds[2];
обхявить их до проверки на интерефейс, тогда не придется лишний раз брать по индексу

2019-01-29 19:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +                    entityInfo.lFieldInfo[NameFildOne.ToString()].lParamInfo.Add(paramInfo);
общие советы  по коду:
1) используй var
2) избегай повторных вызовов методов, в данном случае .ToString.  объяви переменную с понятным названием и дальше уже оперируй ей
3) своди задачу к предыдущей. стремись чтобы условная ветвь заканчивалась а дельше все шло по одному руслу. в данном случае. сделай TryGetValue  если филд все еще =null, создай его, а дальше задание параметра идет по переменной филда. и нет дублироания кода как тебя.
кстати, параметр может переопределяться в наследнике, так что он уже может быть в филде.

2019-02-04 18:39 UTC, troepolik requested changes

2019-02-04 18:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +            if (!entityInfo.lFieldInfo.ContainsKey(NameFildOne.ToString()))
заменить на TryGetValue

2019-02-04 18:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +                entityInfo.lFieldInfo[NameFildOne.ToString()].lParamInfo.Add(paramInfo);
использовать переменную филда, полученную из TryGetValue  выше
и добавить проверку на то что этот параметр не был задан ранее. посмотреть как реализовано в tt

2019-02-04 18:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +                }
а здесь заюзать linq  ты уже не догадался?)

2019-02-04 18:39 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +            var classSymbol = sModel.GetDeclaredSymbol(node);
не знаешь мб из семантической модели можно сразу достать все объявленные классы с определенным условием.
а потом из этих классов достать все объявленные в классе филды или пропертя с определенным условием?
что-то типа лямда выражения - одним запросом достал все классы и филды в них. а потом уже анализировать метод CreateField  - на этом этапе мы уже будем знать весь набор филдов  у сущности,  реализующих интерфейс и не надо будет лишний раз обращаться к модели чтобы узнать что это за филд такой.
если росли такое позволяет, было бы прекрасно, мне кажется код бы стал быстрее работать и понятнее выглядеть

2019-02-09 16:41 UTC, troepolik approved these changes
норм, удали плиз старый вариант анализа, можешь пока у себя где-нить оставить, ато он меня путает.
жду от тебя реализацию графа.

2019-02-09 16:41 UTC, merged