Analisys
meogol/Diplom pull request #2
Opened 2019-03-19 05:51 UTC by meogol

2019-03-25 10:36 UTC, troepolik requested changes
а где сгенерированный результат?

2019-03-25 10:36 UTC, troepolik commented on Generator/T4Generator.tt
> +        }
что тут происходит? я не понимаю... начиная со строчки 
// List<ParamInfo> lParamInfo- лист зависимостей филда. параметр типа? передается в сгенерированный лист

2019-03-26 15:06 UTC, troepolik requested changes

2019-03-26 15:06 UTC, troepolik commented on Generator/T4Generator.tt
> +				{"", new List<CalcFieldInfo>()
у тебя генерится только input - порядок, это в каком порядке вводить значения при загрузке извне.
да и то неправильно генерится т.к не учитывается порядок а ты просто пробежался по всем филдам.
итак же не генерятся порядок пересчет при изменении любого из филдов.
ты даже граф не построил. я тебе библиотечку Framework  присылал для этого. посмотри еще раз как это делается в моих tt  файлах  и как используется эта библиотечка при построении OrientedGraph

2019-04-10 06:46 UTC, troepolik approved these changes

2019-04-24 05:50 UTC, troepolik requested changes

2019-04-24 05:50 UTC, troepolik commented on ProjectAnalisys/EntityTest2.cs
> +    public class EntityTest2 : Entity, ITest2, IFieldsEntity
зачем наследника снова наследовать от интерфейса? базовый класс уже наследуется от него. это просто по запарке или без этого работать не будет?

2019-04-24 05:50 UTC, troepolik commented on ProjectAnalisys/EntityyTest4.cs
> +        static private void CreateFilds()
с чего она вдруг стала статической???

2019-04-24 05:50 UTC, troepolik commented on ProjectAnalisys/EntityyTest4.cs
> +            fild3_1.fild3 = fild3;
я из всех твоих примеров не вижу ниодного где бы ты брал филд из базового класса и добавлял к нему зависимости. подготовь такой пример.
+ у тебя все филды создаются прямо в CreateFilds, это неудобно т.к доступ к ним требуется в других методах тоже.
филды должны создаваться и объявляться на уровне класса , а в CreateFilds им просто дописываются параметры.
например 
clss entity
{
public Field1 field1 {get; set;} = new Field1();
public Field2 field2 {get; set;} = new Field2();
protected virtual void CreateFilds()
{
field1.param = field2;
}
}

2019-04-24 05:50 UTC, troepolik commented on Generator/T4Helper.cs
> +            foreach (var clases in entity)
ты построил код так как будто у тебя энтити будут приходить в него в порядке наследования от базового класса и дальше, чем гарантируется что они не придут в обратном порядке?:
C,B,A -  где C от В, В от А
посмотри мою реализацию построения иерархии, она намного сложнее именно поэтому. сначала нужно посмторить иерархию а потом пройтись по ней,начиная с самого базового класса

2019-04-24 10:44 UTC, meogol commented
переделал

ср, 24 апр. 2019 г. в 08:50, Aleksey Troepolskiy <notifications@github.com>:

> *@troepolik* requested changes on this pull request.
> ------------------------------
>
> In ProjectAnalisys/EntityTest2.cs
> <https://github.com/meogol/Diplom/pull/2#discussion_r277961051>:
>
> > @@ -0,0 +1,22 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace ConsoleApp2
> +{
> +    public class EntityTest2 : Entity, ITest2, IFieldsEntity
>
> зачем наследника снова наследовать от интерфейса? базовый класс уже
> наследуется от него. это просто по запарке или без этого работать не будет?
> ------------------------------
>
> In ProjectAnalisys/EntityyTest4.cs
> <https://github.com/meogol/Diplom/pull/2#discussion_r277961918>:
>
> > @@ -0,0 +1,34 @@
> +﻿using System;
> +using System.Collections.Generic;
> +using System.Linq;
> +using System.Text;
> +using System.Threading.Tasks;
> +
> +namespace ConsoleApp2
> +{
> +    public class EntityyTest4 : EntityTest3
> +    {
> +
> +        static private void CreateFilds()
>
> с чего она вдруг стала статической???
> ------------------------------
>
> In ProjectAnalisys/EntityyTest4.cs
> <https://github.com/meogol/Diplom/pull/2#discussion_r277962128>:
>
> > +
> +
> +            fild1.fild2 = fild22;
> +
> +            Fild3 fild3 = new Fild3();
> +            Fild3_1 fild3_1 = new Fild3_1();
> +
> +            fild3.fild1 = fild1;
> +
> +            TestFild testFild = new TestFild();
> +            Fild3_2 fild3_2 = new Fild3_2();
> +
> +            testFild.fild1 = fild1;
> +
> +            fild3.fild2 = fild22;
> +            fild3_1.fild3 = fild3;
>
> я из всех твоих примеров не вижу ниодного где бы ты брал филд из базового
> класса и добавлял к нему зависимости. подготовь такой пример.
>
>    - у тебя все филды создаются прямо в CreateFilds, это неудобно т.к
>    доступ к ним требуется в других методах тоже.
>    филды должны создаваться и объявляться на уровне класса , а в
>    CreateFilds им просто дописываются параметры.
>    например
>    clss entity
>    {
>    public Field1 field1 {get; set;} = new Field1();
>    public Field2 field2 {get; set;} = new Field2();
>    protected virtual void CreateFilds()
>    {
>    field1.param = field2;
>    }
>    }
>
> ------------------------------
>
> In Generator/T4Helper.cs
> <https://github.com/meogol/Diplom/pull/2#discussion_r277962916>:
>
> > @@ -14,6 +14,31 @@ partial class T4Generator
>          public T4Generator(List<EntityInfo> Entity)
>          {
>              entity = Entity;
> +            AddBaseField();
> +        }
> +
> +        /// <summary>
> +        /// Находим родителя для наследника и проверяем список филдов в наследнике. Если филд уже существует в списке
> +        /// наследника, объединяем его зависимости с зависимостями родителя, в противном случае добавляем филд в список
> +        /// наследника. Метод выполняется перед началом генерации.
> +        /// </summary>
> +        private void AddBaseField()
> +        {
> +            foreach (var clases in entity)
>
> ты построил код так как будто у тебя энтити будут приходить в него в
> порядке наследования от базового класса и дальше, чем гарантируется что они
> не придут в обратном порядке?:
> C,B,A - где C от В, В от А
> посмотри мою реализацию построения иерархии, она намного сложнее именно
> поэтому. сначала нужно посмторить иерархию а потом пройтись по ней,начиная
> с самого базового класса
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/meogol/Diplom/pull/2#pullrequestreview-229906625>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AGUY7QGFOY23FHYTSWZNUNTPR7YKZANCNFSM4G7NK7OQ>
> .
>

2019-04-29 10:02 UTC, troepolik requested changes

2019-04-29 10:02 UTC, troepolik commented on Analisys/AnalisysCode.cs
> +                        entityInfo.baseClassName = baseClassSyntax.FirstOrDefault().ToString();
ничего не понял. что за проверка, для чего она, коментарий мутный и длинный.
пиши коментарии над условием в несколько строк если они длинные, приведи пример чего хочешь избежать.
я так понял тебе из синтаксиса базового класса надо выдернуть базовый класс, откинув все интерефейсы.
если это так, то эта проверка какая-то говеная...

2019-04-29 10:02 UTC, troepolik commented on Generator/T4Helper.cs
> +            foreach (var entityClass in entity)
зачем трогать глобальный список энтитей? он передается в класс и мало ли где используется еще по ссылке, а ты взял и весь список очистил- плохое решение. либо передавать клон в параметры метода либо переделывай алгоритм.

2019-04-29 10:02 UTC, troepolik commented on Generator/T4Helper.cs
> +                BuildHierarhi(hierarhi);
в твоем алгоритме теряется весь смыл рекурсивного подхода, можно было просто сделать While(entity.Count != 0)
и крутить это колесо пока не умрем.
у тебя получился очень дорогой алгоритм, мы на каждой итерации проходим все энтити.  и все базовый классы.
лучше для всех переданных в метод базовых классов находить наследников, прописывать ссылки, а затем найденных наследников передавать снова в BuildHierarhi (parentClasses)
что вернулось из BuildHierarhi добавлять в список на возврат и так пока BuildHierarhi вернет не пустой список.

2019-04-29 10:02 UTC, troepolik commented on Generator/T4Helper.cs
> +        /// выстраиваем список таким образом, чтобы первыми эллементами были родители, а последними наследники.
желательно чтобы он не только выстраивал по порядку, а прописывать ссылки на базовую энтитю и на наследничков. для этого у меня был класс HierarhiNode

2019-05-06 09:37 UTC, troepolik requested changes

2019-05-06 09:37 UTC, troepolik commented on Analisys/AnalisysCode.cs
>                      if (baseClassSyntax.FirstOrDefault() != null)
я опять из коментария мало что понял, видимо задача проверить реализует ли базовый класс интерфейс IFieldsEntity ? и если не реализует, то не записывать его в базовые классы?
тогда может это и надо проверять?
также видимо тебе нужно проверить является ли эта нода классом или интерефейсом. - это можно леально проверить?
типа функцию написать IsClassNode() 
также помню у нас была ф-я проверки реализует ли данный класс интерфейс, её здесь тоже можно задействовать, а не писать невероятные условия, кстати, а зачем тут вложенный if  если можно написать через "и"

2019-05-15 06:38 UTC, troepolik approved these changes

2019-05-15 06:38 UTC, merged